name: Release Staging

on:
  pull_request:
    types: [closed]
    branches:
      - main # or your default branch name
  workflow_dispatch: # Add manual trigger

jobs:
  trigger-infra-workflow:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Get CI Bot Token
        uses: tibdex/github-app-token@v2
        id: ci_bot_token
        with:
          app_id: ${{ secrets.CI_BOT_APP_ID }}
          private_key: ${{ secrets.CI_BOT_SECRET }}

      - name: Trigger Infra Deploy Studio to Staging Environment
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ steps.ci_bot_token.outputs.token }}" \
            https://api.github.com/repos/yeagerai/genlayer-infra/actions/workflows/deploy-stage.yml/dispatches \
            -d '{"ref":"main"}'
